Repository NHSDigital/validated-relationships-service-api, pull requests merged in 2024-05, with the labels that each got.

#60 NPA-2797 Update Sandbox for All Errors Have Correct Mime Type
  proxies/sandbox/apiproxy/policies/AssignMessage.SetMimeType.xml
  proxies/sandbox/apiproxy/policies/RaiseFault.400BadRequest.xml
  proxies/sandbox/apiproxy/policies/RaiseFault.401Unauthorized.xml
  proxies/sandbox/apiproxy/policies/RaiseFault.DefaultError.xml
  proxies/sandbox/apiproxy/targets/sandbox.xml
Labels: enhancement

#62 NPA-2619 Update Dependabot Configuration to Version 2
  .dependabot/config.yml
  .github/dependabot.yml
Labels: dependencies

#67 NPA-2619 Group All Dependencies Updates
  .github/dependabot.yml
  .github/workflows/continuous-integration.yml
  package-lock.json
  package.json
  poetry.lock
  sandbox/poetry.lock
  sandbox/pyproject.toml
Labels: dependencies

#76 NPA-1736: Added postman collection to repo for versioning
  postman/Validate Relationship Service Sandbox.postman_collection.json
Labels: documentation
