Repository NHSDigital/validated-relationships-service-api, pull requests merged in 2025-06, with the labels that each got.

#212 NPA-5016: Bump specification Version to 1.5.0
  specification/validated-relationships-service-api.yaml
Labels: documentation

#213 NPA-5086 Add GET /Consent/{id} endpoint
  .github/workflows/openapi-validate.yml
  Makefile
  specification/examples/responses/GET_Consent/ID/errors/invalid-id.yaml
  specification/examples/responses/GET_Consent/ID/errors/missing-id.yaml
  specification/validated-relationships-service-api.yaml
Labels: documentation, enhancement, github_actions

#215 NPA-5086 Fix OAS Grammar Issue
  specification/validated-relationships-service-api.yaml
Labels: bug, documentation

#224 NPA-5116 Add API Authentication Documentation
  specification/validated-relationships-service-api.yaml
Labels: documentation, enhancement

#227 NPA-4330: Improve PR Template
  .github/pull_request_template.md
Labels: documentation, github_actions
