Repository NHSDigital/validated-relationships-service-api, pull requests merged in 2025-09, with the labels that each got.

#250 NPA-5212: version bump V.11.0
  specification/validated-relationships-service-api.yaml
Labels: documentation

#252 NPA-5559: IOPS Amendments to GET RelatedPerson
  postman/Validated Relationship Service Sandbox.postman_collection.json
  specification/examples/responses/GET_RelatedPerson/list_relationship_9000000017.yaml
  specification/examples/responses/GET_RelatedPerson/list_relationship_9000000017_include.yaml
  specification/examples/responses/GET_RelatedPerson/list_relationship_9000000042.yaml
  specification/examples/responses/GET_RelatedPerson/list_relationship_9000000042_include.yaml
  specification/examples/responses/GET_RelatedPerson/verify_relationship_9000000009.yaml
  specification/examples/responses/GET_RelatedPerson/verify_relationship_9000000009_include.yaml
  specification/examples/responses/GET_RelatedPerson/verify_relationship_9000000025.yaml
  specification/examples/responses/GET_RelatedPerson/verify_relationship_9000000025_include.yaml
  specification/validated-relationships-service-api.yaml
Labels: documentation, postman

#255 NPA-5664: Version spec bump to V1.13.0
  specification/validated-relationships-service-api.yaml
Labels: documentation

#257 NPA-5565: Update the Sandbox test scenarios table
  .github/pull_request_template.md
  .gitignore
  specification/validated-relationships-service-api.yaml
Labels: documentation, enhancement, OAS

#258 NPA-5715: Fix Postman Collection
  .github/workflows/run-postman-collection.yml
  sandbox/README.md
Labels: bug, postman
