Repository NHSDigital/validated-relationships-service-api, pull requests merged in 2025-02, with the labels that each got.

#136 NPA-4262 Restrict Evidence of Responsibility to Single Option
  .github/pull_request_template.md
  specification/validated-relationships-service-api.yaml
Labels: bug, documentation

#140 NPA-3895: Added GitHub action to run schema validation
  .github/workflows/openapi-validate.yml
  Makefile
  poetry.lock
  pyproject.toml
  scripts/validate_schema.py
  specification/examples/responses/GET_Consent/filtered-relationships-status-active-include-details.yaml
  specification/examples/responses/GET_Consent/multiple-relationships-include-performer-patient.yaml
  specification/examples/responses/GET_Consent/multiple-relationships-include-performer.yaml
  specification/examples/responses/GET_Consent/single-mother-child-relationship-include-performer-patient.yaml
  specification/examples/responses/GET_RelatedPerson/list_relationship_9000000017.yaml
  specification/examples/responses/GET_RelatedPerson/list_relationship_9000000017_include.yaml
  specification/examples/responses/GET_RelatedPerson/verify_relationship_9000000009.yaml
  specification/examples/responses/GET_RelatedPerson/verify_relationship_9000000009_include.yaml
  specification/examples/responses/GET_RelatedPerson/verify_relationship_9000000025.yaml
  specification/examples/responses/GET_RelatedPerson/verify_relationship_9000000025_include.yaml
  specification/validated-relationships-service-api.yaml
Labels: enhancement, github_actions

#143 NPA-4421: Remove Duplicate Internal QA Environment
  manifest_template.yml
Labels: bug

#144 NPA-4421 Increase Rate Limits to 10 Per Second
  manifest_template.yml
Labels: enhancement
