Repository NHSDigital/validated-relationships-service-api, pull requests merged in 2025-04, with the labels that each got.

#166 NPA-4607 Add PATCH /FHIR/R4/Consent 5XX Errors
  specification/validated-relationships-service-api.yaml
Labels: enhancement, dependencies

#168 NPA-4610 Remove Extra Ops
  specification/validated-relationships-service-api.yaml
Labels: documentation

#167 NPA-4599: Added App Restricted Authentication
  .flake8
  manifest_template.yml
  proxies/live/apiproxy/policies/AssignMessage.AddAuthHeaders.xml
  proxies/live/apiproxy/policies/CheckAppEnabledEndpoint.xml
  proxies/live/apiproxy/policies/CheckUserEnabledEndpoint.xml
  proxies/live/apiproxy/policies/OAuthV2.VerifyAccessTokenUser.xml
  proxies/live/apiproxy/resources/py/check-app-enabled-endpoint.py
  proxies/live/apiproxy/resources/py/check-user-enabled-endpoint.py
  proxies/live/apiproxy/targets/target.xml
Labels: enhancement, python

#170 NPA-4706: Mark POST Consent Keys As Required
  specification/validated-relationships-service-api.yaml
Labels: bug

#176 NPA-4599: Update python scripts to check path suffix contains rather than equals specific string to account for path parameters
  proxies/live/apiproxy/resources/py/check-app-enabled-endpoint.py
  proxies/live/apiproxy/resources/py/check-user-enabled-endpoint.py
Labels: bug

#183 NPA-4689 Refactor Sandbox Endpoints into Separate Files
  sandbox/api/app.py
  sandbox/api/get_consent.py
  sandbox/api/get_related_person.py
  sandbox/api/patch_consent.py
  sandbox/api/post_consent.py
  sandbox/api/post_questionnaire_response.py
  sandbox/api/tests/conftest.py
  sandbox/api/tests/test_app.py
  sandbox/api/tests/test_get_consent.py
  sandbox/api/tests/test_get_related_person.py
  sandbox/api/tests/test_patch_consent.py
  sandbox/api/tests/test_post_consent.py
  sandbox/api/tests/test_post_questionnaire_response.py
  sandbox/api/tests/test_utils.py
  sandbox/api/utils.py
Labels: enhancement, python

#184 NPA-4689 Add `GET /QuestionnaireResponse` Endpoint To Sandbox
  .github/workflows/openapi-validate.yml
  .github/workflows/run-postman-collection.yml
  .github/workflows/sandbox-checks.yaml
  sandbox/api/app.py
  sandbox/api/constants.py
  sandbox/api/get_consent.py
  sandbox/api/get_questionnaire_response.py
  sandbox/api/post_questionnaire_response.py
  sandbox/api/tests/test_get_questionnaire_response.py
  specification/validated-relationships-service-api.yaml
Labels: enhancement, python

#185 NPA-4689 Update Postman Collection with GET /QuestionnaireResponse Sandbox Endpoint
  postman/Validate Relationship Service Sandbox.postman_collection.json
  sandbox/api/constants.py
  sandbox/api/tests/test_get_questionnaire_response.py
  specification/validated-relationships-service-api.yaml
Labels: enhancement

#186 NPA-4693 Fix MISSING_REFERENCE_CODE Sandbox Response
  sandbox/api/get_questionnaire_response.py
  sandbox/api/tests/test_get_questionnaire_response.py
Labels: bug, python

#187 NPA-4670: Add App Header to Auth Header Policy
  proxies/live/apiproxy/policies/AssignMessage.AddAuthHeaders.xml
Labels: documentation

#189 NPA-4824: Add INVALID_STATUS_REASON Error
  sandbox/api/constants.py
  sandbox/api/patch_consent.py
  sandbox/api/tests/test_patch_consent.py
  specification/examples/responses/PATCH_Consent/errors/invalid_status_reason.yaml
  specification/validated-relationships-service-api.yaml
Labels: documentation

#190 NPA-4705: New INVALID_EXTENSION error added to POST Consent
  specification/validated-relationships-service-api.yaml
Labels: bug

#191 NPA-4737 Fix Markdown Tables
  specification/validated-relationships-service-api.yaml
Labels: bug, documentation

#194 NPA-4907 Enforce Single Performer Item
  specification/validated-relationships-service-api.yaml
Labels: documentation, enhancement
