Repository NHSDigital/validated-relationships-service-api, pull requests merged in 2025-03, with the labels that each got.

#147 NPA-4511: Sandbox for POST Consent
  .github/workflows/openapi-validate.yml
  Makefile
  sandbox/Makefile
  sandbox/api/app.py
  sandbox/api/constants.py
  sandbox/api/tests/test_app.py
  sandbox/api/tests/test_utils.py
  sandbox/api/utils.py
  scripts/calculate_version.py
  scripts/validate_schema.py
  specification/examples/requests/POST_Consent/adult_to_adult_proxy_creation.yaml
  specification/examples/requests/POST_Consent/parent_child_proxy_creation.yaml
  specification/examples/responses/POST_Consent/error.yaml
  specification/examples/responses/POST_Consent/errors/duplicate_relationship_error.yaml
  specification/examples/responses/POST_Consent/errors/invalid_access_level_error.yaml
  specification/examples/responses/POST_Consent/errors/invalid_evidence_error.yaml
  specification/examples/responses/POST_Consent/errors/invalid_patient_age_error.yaml
  specification/examples/responses/POST_Consent/errors/invalid_performer_identifier_error.yaml
  specification/validated-relationships-service-api.yaml
  tests/test_endpoints.py
Labels: documentation, enhancement, python

#148 NPA-4511: sandbox consent post
  sandbox/api/constants.py
Labels: python

#149 NPA-4511: Postman collection added
  postman/Validate_Relationship_Service_Sandbox.postman_collection.json
  specification/validated-relationships-service-api.yaml
Labels: enhancement

#146 NPA-4474 Add new GET /Consent status codes
  poetry.lock
  pyproject.toml
  sandbox/Makefile
  sandbox/api/app.py
  sandbox/api/get_consent.py
  sandbox/api/tests/test_app.py
  sandbox/api/tests/test_utils.py
  sandbox/api/utils.py
  sandbox/poetry.lock
  specification/examples/responses/GET_Consent/errors/downstream-service-error.yaml
  specification/examples/responses/GET_Consent/errors/gp-practice-not-found.yaml
  specification/examples/responses/GET_Consent/errors/invalid-identifier-system.yaml
  specification/examples/responses/GET_Consent/errors/invalid-identifier.yaml
  specification/examples/responses/GET_Consent/errors/invalid-status-parameter.yaml
  specification/validated-relationships-service-api.yaml
Labels: bug, documentation, enhancement, python

#153 NPA-4423: Postman tests reviewed
  .github/workflows/run-postman-collection.yml
  postman/Validate Relationship Service Sandbox.postman_collection.json
  specification/validated-relationships-service-api.yaml
Labels: bug, github_actions

#154 NPA-4517: Added headers
  specification/validated-relationships-service-api.yaml
Labels: enhancement

#155 NPA-4513 Update POST /FHIR/R4/Consent 4XX Status Codes
  sandbox/api/app.py
  sandbox/api/tests/test_app.py
  specification/validated-relationships-service-api.yaml
Labels: enhancement, python

#157 NPA-4557: Add 5XX Error responses to OAS spec for POST Consent
  specification/examples/responses/errors/downstream-service-error.yaml
  specification/validated-relationships-service-api.yaml
Labels: documentation

#156 NPA-4514 Update POST /FHIR/R4/Consent Status Codes
  sandbox/api/app.py
  sandbox/api/constants.py
  sandbox/api/tests/test_app.py
  specification/examples/responses/POST_Consent/errors/invalid_access_level_error.yaml
  specification/examples/responses/POST_Consent/errors/invalid_evidence_error.yaml
  specification/examples/responses/POST_Consent/errors/invalid_patient_age_error.yaml
  specification/examples/responses/POST_Consent/errors/invalid_performer_identifier_error.yaml
  specification/validated-relationships-service-api.yaml
Labels: bug, documentation, enhancement, python

#158 NPA-4514: Update Postman Collection
  postman/Validate Relationship Service Sandbox.postman_collection.json
  specification/validated-relationships-service-api.yaml
Labels: bug

#160 NPA-4513 Update POST /FHIR/R4/Consent Request and Errors
  specification/validated-relationships-service-api.yaml
Labels: enhancement

#162 NPA-4513 Expand POST /Consent Error Examples
  specification/examples/responses/POST_Consent/errors/duplicate_relationship_error.yaml
  specification/examples/responses/POST_Consent/errors/invalid_identifier_value.yaml
  specification/examples/responses/POST_Consent/errors/invalid_performer_identifier_error.yaml
  specification/examples/responses/POST_Consent/errors/invalid_status.yaml
  specification/examples/responses/POST_Consent/errors/missing_identifier_system.yaml
  specification/examples/responses/POST_Consent/errors/missing_scope.yaml
  specification/validated-relationships-service-api.yaml
Labels: enhancement

#159 NPA-4513 Update Authentication Error
  proxies/live/apiproxy/policies/RaiseFault.403Forbidden.xml
  proxies/live/apiproxy/targets/target.xml
Labels: enhancement

#163 NPA-4575: Update sandbox with consent patch
  .github/workflows/openapi-validate.yml
  Makefile
  postman/Validate Relationship Service Sandbox.postman_collection.json
  sandbox/Makefile
  sandbox/api/app.py
  sandbox/api/constants.py
  sandbox/api/tests/test_app.py
  specification/examples/responses/PATCH_Consent/error.yaml
  specification/examples/responses/PATCH_Consent/errors/invalid_patch_format.yaml
  specification/examples/responses/PATCH_Consent/errors/invalid_path.yaml
  specification/examples/responses/PATCH_Consent/errors/invalid_state_transition.yaml
  specification/examples/responses/PATCH_Consent/errors/invalid_status_code.yaml
  specification/examples/responses/PATCH_Consent/errors/resource_not_found.yaml
  specification/validated-relationships-service-api.yaml
Labels: documentation, enhancement, python, postman

#164 NPA-4688: Add GET /FHIR/R4/QuestionnaireResponse
  .github/workflows/openapi-validate.yml
  Makefile
  postman/Validate Relationship Service Sandbox.postman_collection.json
  scripts/validate_schema.py
  specification/examples/responses/GET_QuestionnaireResponse/errors/invalid_reference_code.yaml
  specification/examples/responses/GET_QuestionnaireResponse/errors/missing_reference_code.yaml
  specification/examples/responses/GET_QuestionnaireResponse/errors/questionnaire_response_not_found.yaml
  specification/examples/responses/GET_QuestionnaireResponse/success.yaml
  specification/examples/responses/POST_QuestionnaireResponse/success.yaml
  specification/validated-relationships-service-api.yaml
Labels: documentation, enhancement
